FROM rust:1.93.0-alpine3.20 AS chef
USER root
RUN apk add --no-cache musl-dev & cargo install cargo-chef
WORKDIR /auth-micro

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /auth-micro/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
RUN apk add --no-cache protoc
COPY . .
RUN cargo build --release --bin health-check

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR /auth-micro
COPY --from=builder /auth-micro/target/release/health-check /usr/local/bin
ENV AUTH_SERVICE_HOST_NAME=auth
ENTRYPOINT ["/usr/local/bin/health-check"]
